export interface AlphabetItem {
  letter: string;
  type: 'consonant' | 'vowel';
  consonantClass?: 'low' | 'mid' | 'high';
  exampleWord: string;
  exampleTranslation: string;
  exampleTranslationEn?: string;
  pronunciation: string; // The pronunciation of the example word, e.g. "ko kai"
  mnemonicHintFr?: string;
  mnemonicHintEn?: string;
  mnemonicEmoji?: string;
}

export const THAI_ALPHABET: AlphabetItem[] = [
  // Consonants (Selection of most common ones for a start, but we can list all 44)
  { letter: "ก", type: "consonant", consonantClass: "mid", exampleWord: "ก ไก่", exampleTranslation: "Poulet", exampleTranslationEn: "Chicken", pronunciation: "kɔɔ kài", mnemonicHintFr: "Un bec de poulet", mnemonicHintEn: "A chicken beak", mnemonicEmoji: "🐔" },
  { letter: "ข", type: "consonant", consonantClass: "high", exampleWord: "ข ไข่", exampleTranslation: "Œuf", exampleTranslationEn: "Egg", pronunciation: "khɔ̌ɔ khài", mnemonicHintFr: "Un œuf cassé", mnemonicHintEn: "A broken egg", mnemonicEmoji: "🥚" },
  { letter: "ค", type: "consonant", consonantClass: "low", exampleWord: "ค ควาย", exampleTranslation: "Buffle", exampleTranslationEn: "Buffalo", pronunciation: "khɔɔ khwaai", mnemonicHintFr: "Les cornes d'un buffle", mnemonicHintEn: "Buffalo horns", mnemonicEmoji: "🐃" },
  { letter: "ง", type: "consonant", consonantClass: "low", exampleWord: "ง งู", exampleTranslation: "Serpent", exampleTranslationEn: "Snake", pronunciation: "ngɔɔ nguu", mnemonicHintFr: "Un serpent qui se dresse", mnemonicHintEn: "A standing snake", mnemonicEmoji: "🐍" },
  { letter: "จ", type: "consonant", consonantClass: "mid", exampleWord: "จ จาน", exampleTranslation: "Assiette", exampleTranslationEn: "Plate", pronunciation: "jɔɔ jaan", mnemonicHintFr: "Une assiette filante", mnemonicHintEn: "A spinning plate", mnemonicEmoji: "🍽️" },
  { letter: "ฉ", type: "consonant", consonantClass: "high", exampleWord: "ฉ ฉิ่ง", exampleTranslation: "Cymbales", exampleTranslationEn: "Cymbals", pronunciation: "chɔ̌ɔ chìng", mnemonicHintFr: "Deux cymbales qui se frappent", mnemonicHintEn: "Clashing cymbals", mnemonicEmoji: "🥁" },
  { letter: "ช", type: "consonant", consonantClass: "low", exampleWord: "ช ช้าง", exampleTranslation: "Éléphant", exampleTranslationEn: "Elephant", pronunciation: "chɔɔ cháang", mnemonicHintFr: "La trompe d'un éléphant", mnemonicHintEn: "An elephant trunk", mnemonicEmoji: "🐘" },
  { letter: "ซ", type: "consonant", consonantClass: "low", exampleWord: "ซ โซ่", exampleTranslation: "Chaîne", exampleTranslationEn: "Chain", pronunciation: "sɔɔ sôo", mnemonicHintFr: "Une chaîne brisée", mnemonicHintEn: "A broken chain", mnemonicEmoji: "⛓️" },
  { letter: "ญ", type: "consonant", consonantClass: "low", exampleWord: "ญ หญิง", exampleTranslation: "Femme", exampleTranslationEn: "Woman", pronunciation: "yɔɔ yǐng", mnemonicHintFr: "Une femme gracieuse", mnemonicHintEn: "A graceful woman", mnemonicEmoji: "👩" },
  { letter: "ด", type: "consonant", consonantClass: "mid", exampleWord: "ด เด็ก", exampleTranslation: "Enfant", exampleTranslationEn: "Child", pronunciation: "dɔɔ dèk", mnemonicHintFr: "Un enfant qui court", mnemonicHintEn: "A running child", mnemonicEmoji: "👦" },
  { letter: "ต", type: "consonant", consonantClass: "mid", exampleWord: "ต เต่า", exampleTranslation: "Tortue", exampleTranslationEn: "Turtle", pronunciation: "dtɔɔ dtào", mnemonicHintFr: "Une carapace de tortue", mnemonicHintEn: "A turtle shell", mnemonicEmoji: "🐢" },
  { letter: "ถ", type: "consonant", consonantClass: "high", exampleWord: "ถ ถุง", exampleTranslation: "Sac", exampleTranslationEn: "Sack", pronunciation: "thɔ̌ɔ thǔng", mnemonicHintFr: "Un sac avec une boucle ouverte", mnemonicHintEn: "A sack with an open loop", mnemonicEmoji: "🛍️" },
  { letter: "ท", type: "consonant", consonantClass: "low", exampleWord: "ท ทหาร", exampleTranslation: "Soldat", exampleTranslationEn: "Soldier", pronunciation: "thɔɔ thá-haan", mnemonicHintFr: "Un soldat debout", mnemonicHintEn: "A standing soldier", mnemonicEmoji: "🪖" },
  { letter: "ธ", type: "consonant", consonantClass: "low", exampleWord: "ธ ธง", exampleTranslation: "Drapeau", exampleTranslationEn: "Flag", pronunciation: "thɔɔ thong", mnemonicHintFr: "Un drapeau qui flotte", mnemonicHintEn: "A waving flag", mnemonicEmoji: "🚩" },
  { letter: "น", type: "consonant", consonantClass: "low", exampleWord: "น หนู", exampleTranslation: "Souris", exampleTranslationEn: "Mouse", pronunciation: "nɔɔ nǔu", mnemonicHintFr: "Une petite souris", mnemonicHintEn: "A small mouse", mnemonicEmoji: "🐭" },
  { letter: "บ", type: "consonant", consonantClass: "mid", exampleWord: "บ ใบไม้", exampleTranslation: "Feuille", exampleTranslationEn: "Leaf", pronunciation: "bɔɔ bai-máai", mnemonicHintFr: "Une feuille large", mnemonicHintEn: "A wide leaf", mnemonicEmoji: "🍃" },
  { letter: "ป", type: "consonant", consonantClass: "mid", exampleWord: "ป ปลา", exampleTranslation: "Poisson", exampleTranslationEn: "Fish", pronunciation: "bpɔɔ bplaa", mnemonicHintFr: "La queue d'un poisson", mnemonicHintEn: "A fish tail", mnemonicEmoji: "🐟" },
  { letter: "ผ", type: "consonant", consonantClass: "high", exampleWord: "ผ ผึ้ง", exampleTranslation: "Abeille", exampleTranslationEn: "Bee", pronunciation: "phɔ̌ɔ phueng", mnemonicHintFr: "Le vol en W d'une abeille", mnemonicHintEn: "W-shaped flight of a bee", mnemonicEmoji: "🐝" },
  { letter: "ฝ", type: "consonant", consonantClass: "high", exampleWord: "ฝ ฝา", exampleTranslation: "Couvercle", exampleTranslationEn: "Lid", pronunciation: "fɔ̌ɔ fǎa", mnemonicHintFr: "Un couvercle avec poignée", mnemonicHintEn: "A lid with a handle", mnemonicEmoji: "🥘" },
  { letter: "พ", type: "consonant", consonantClass: "low", exampleWord: "พ พาน", exampleTranslation: "Plateau", exampleTranslationEn: "Tray", pronunciation: "phɔɔ phaan", mnemonicHintFr: "Un trophée (qui rappelle le plateau)", mnemonicHintEn: "A trophy (resembling the pedestal tray)", mnemonicEmoji: "🏆" },
  { letter: "ฟ", type: "consonant", consonantClass: "low", exampleWord: "ฟ ฟัน", exampleTranslation: "Dent", exampleTranslationEn: "Tooth", pronunciation: "fɔɔ fan", mnemonicHintFr: "Une longue dent piquante", mnemonicHintEn: "A long sharp tooth", mnemonicEmoji: "🦷" },
  { letter: "ภ", type: "consonant", consonantClass: "low", exampleWord: "ภ สำเภา", exampleTranslation: "Jonque", exampleTranslationEn: "Junk", pronunciation: "phɔɔ sǎm-phao", mnemonicHintFr: "La voile d'une jonque", mnemonicHintEn: "A junk boat's sail", mnemonicEmoji: "⛵" },
  { letter: "ม", type: "consonant", consonantClass: "low", exampleWord: "ม ม้า", exampleTranslation: "Cheval", exampleTranslationEn: "Horse", pronunciation: "mɔɔ máa", mnemonicHintFr: "Un cheval qui s'étire", mnemonicHintEn: "A stretching horse", mnemonicEmoji: "🐴" },
  { letter: "ย", type: "consonant", consonantClass: "low", exampleWord: "ย ยักษ์", exampleTranslation: "Géant", exampleTranslationEn: "Giant", pronunciation: "yɔɔ yák", mnemonicHintFr: "Un géant tordu", mnemonicHintEn: "A twisted giant", mnemonicEmoji: "👹" },
  { letter: "ร", type: "consonant", consonantClass: "low", exampleWord: "ร เรือ", exampleTranslation: "Bateau", exampleTranslationEn: "Boat", pronunciation: "rɔɔ ruea", mnemonicHintFr: "L'avant d'un bateau", mnemonicHintEn: "The front of a boat", mnemonicEmoji: "🚤" },
  { letter: "ล", type: "consonant", consonantClass: "low", exampleWord: "ล ลิง", exampleTranslation: "Singe", exampleTranslationEn: "Monkey", pronunciation: "lɔɔ ling", mnemonicHintFr: "Un singe suspendu", mnemonicHintEn: "A hanging monkey", mnemonicEmoji: "🐒" },
  { letter: "ว", type: "consonant", consonantClass: "low", exampleWord: "ว แหวน", exampleTranslation: "Bague", exampleTranslationEn: "Ring", pronunciation: "wɔɔ wǎen", mnemonicHintFr: "Une bague ronde", mnemonicHintEn: "A round ring", mnemonicEmoji: "💍" },
  { letter: "ศ", type: "consonant", consonantClass: "high", exampleWord: "ศ ศาลา", exampleTranslation: "Pavillon", exampleTranslationEn: "Pavilion", pronunciation: "sɔ̌ɔ sǎa-laa", mnemonicHintFr: "Un long pavillon", mnemonicHintEn: "A tall pavilion", mnemonicEmoji: "🛕" },
  { letter: "ษ", type: "consonant", consonantClass: "high", exampleWord: "ษ ฤๅษี", exampleTranslation: "Ermite", exampleTranslationEn: "Hermit", pronunciation: "sɔ̌ɔ rǔe-sǐi", mnemonicHintFr: "La canne d'un ermite", mnemonicHintEn: "A hermit's cane", mnemonicEmoji: "🧙" },
  { letter: "ส", type: "consonant", consonantClass: "high", exampleWord: "ส เสือ", exampleTranslation: "Tigre", exampleTranslationEn: "Tiger", pronunciation: "sɔ̌ɔ sǔea", mnemonicHintFr: "La queue d'un tigre", mnemonicHintEn: "A tiger's tail", mnemonicEmoji: "🐅" },
  { letter: "ห", type: "consonant", consonantClass: "high", exampleWord: "ห หีบ", exampleTranslation: "Coffre", exampleTranslationEn: "Chest", pronunciation: "hɔ̌ɔ hìip", mnemonicHintFr: "Un coffre ouvert", mnemonicHintEn: "An open chest", mnemonicEmoji: "🧰" },
  { letter: "ฬ", type: "consonant", consonantClass: "low", exampleWord: "ฬ จุฬา", exampleTranslation: "Cerf-volant", exampleTranslationEn: "Kite", pronunciation: "lɔɔ jù-laa", mnemonicHintFr: "Un cerf-volant avec une longue queue", mnemonicHintEn: "A kite with a long tail", mnemonicEmoji: "🪁" },
  { letter: "อ", type: "consonant", consonantClass: "mid", exampleWord: "อ อ่าง", exampleTranslation: "Bassine", exampleTranslationEn: "Basin", pronunciation: "ɔɔ àang", mnemonicHintFr: "Une bassine ronde", mnemonicHintEn: "A round basin", mnemonicEmoji: "🥣" },
  { letter: "ฮ", type: "consonant", consonantClass: "low", exampleWord: "ฮ นกฮูก", exampleTranslation: "Hibou", exampleTranslationEn: "Owl", pronunciation: "hɔɔ nók-hûuk", mnemonicHintFr: "Un hibou perchoir", mnemonicHintEn: "A perched owl", mnemonicEmoji: "🦉" },
  { letter: "ฆ", type: "consonant", consonantClass: "low", exampleWord: "ฆ ระฆัง", exampleTranslation: "Cloche", exampleTranslationEn: "Bell", pronunciation: "khɔɔ rá-khang", mnemonicHintFr: "Une cloche de temple", mnemonicHintEn: "A temple bell", mnemonicEmoji: "🔔" },
  { letter: "ฌ", type: "consonant", consonantClass: "low", exampleWord: "ฌ เฌอ", exampleTranslation: "Arbre", exampleTranslationEn: "Tree", pronunciation: "chɔɔ choe", mnemonicHintFr: "Un arbre touffu", mnemonicHintEn: "A bushy tree", mnemonicEmoji: "🌳" },
  { letter: "ฎ", type: "consonant", consonantClass: "mid", exampleWord: "ฎ ชฎา", exampleTranslation: "Coiffe", exampleTranslationEn: "Headdress", pronunciation: "dɔɔ chá-daa", mnemonicHintFr: "Une coiffe de danseuse", mnemonicHintEn: "A dancer's headdress", mnemonicEmoji: "👑" },
  { letter: "ฏ", type: "consonant", consonantClass: "mid", exampleWord: "ฏ ปฏัก", exampleTranslation: "Javelot", exampleTranslationEn: "Javelin", pronunciation: "dtɔɔ bpà-dtàk", mnemonicHintFr: "Une pointe de javelot", mnemonicHintEn: "A javelin tip", mnemonicEmoji: "🪃" },
  { letter: "ฐ", type: "consonant", consonantClass: "high", exampleWord: "ฐ ฐาน", exampleTranslation: "Piédestal", exampleTranslationEn: "Pedestal", pronunciation: "thɔ̌ɔ thǎan", mnemonicHintFr: "Un piédestal sculpté", mnemonicHintEn: "A sculpted pedestal", mnemonicEmoji: "🏛️" },
  { letter: "ฑ", type: "consonant", consonantClass: "low", exampleWord: "ฑ มณโฑ", exampleTranslation: "Montho", exampleTranslationEn: "Queen Montho", pronunciation: "thɔɔ mon-thoo", mnemonicHintFr: "Une reine mythologique", mnemonicHintEn: "A mythological queen", mnemonicEmoji: "👸" },
  { letter: "ฒ", type: "consonant", consonantClass: "low", exampleWord: "ฒ ผู้เฒ่า", exampleTranslation: "Vieillard", exampleTranslationEn: "Old man", pronunciation: "thɔɔ phûu-thâo", mnemonicHintFr: "Un vieillard voûté", mnemonicHintEn: "A hunched old man", mnemonicEmoji: "👴" },
  { letter: "ณ", type: "consonant", consonantClass: "low", exampleWord: "ณ เณร", exampleTranslation: "Novice", exampleTranslationEn: "Novice monk", pronunciation: "nɔɔ neen", mnemonicHintFr: "Un jeune moine", mnemonicHintEn: "A young monk", mnemonicEmoji: "🦲" },

  // Vowels and symbols
  { letter: "ฤ", type: "vowel", exampleWord: "ฤ", exampleTranslation: "Voyelle rue/ri", exampleTranslationEn: "Vowel rue/ri", pronunciation: "rue / ri", mnemonicHintFr: "Une boucle avec queue", mnemonicHintEn: "A loop with a tail", mnemonicEmoji: "➰" },
  { letter: "ั", type: "vowel", exampleWord: "ไม้หันอากาศ", exampleTranslation: "Voyelle a (courte fermée)", exampleTranslationEn: "Vowel a (closed short)", pronunciation: "mai han-a-kat", mnemonicHintFr: "Un petit oiseau qui vole", mnemonicHintEn: "A little flying bird", mnemonicEmoji: "🕊️" },
  { letter: "ำ", type: "vowel", exampleWord: "สระ อำ", exampleTranslation: "Voyelle am", exampleTranslationEn: "Vowel am", pronunciation: "sara am", mnemonicHintFr: "Un petit cercle", mnemonicHintEn: "A small circle", mnemonicEmoji: "⭕" },
  { letter: "่", type: "vowel", exampleWord: "ไม้เอก", exampleTranslation: "Ton bas", exampleTranslationEn: "Low tone", pronunciation: "mai ek", mnemonicHintFr: "Un petit trait vertical", mnemonicHintEn: "A vertical dash", mnemonicEmoji: "🔽" },
  { letter: "้", type: "vowel", exampleWord: "ไม้โท", exampleTranslation: "Ton descendant", exampleTranslationEn: "Falling tone", pronunciation: "mai tho", mnemonicHintFr: "Un petit crochet", mnemonicHintEn: "A small hook", mnemonicEmoji: "⤵️" },
  { letter: "๊", type: "vowel", exampleWord: "ไม้ตรี", exampleTranslation: "Ton haut", exampleTranslationEn: "High tone", pronunciation: "mai tri", mnemonicHintFr: "Un petit chiffre 7", mnemonicHintEn: "A tiny number 7", mnemonicEmoji: "↗️" },
  { letter: "๋", type: "vowel", exampleWord: "ไม้จัตวา", exampleTranslation: "Ton ascendant", exampleTranslationEn: "Rising tone", pronunciation: "mai chattawa", mnemonicHintFr: "Un petit plus", mnemonicHintEn: "A tiny plus sign", mnemonicEmoji: "➕" },
  { letter: "็", type: "vowel", exampleWord: "ไม้ไต่คู้", exampleTranslation: "Raccourcissement", exampleTranslationEn: "Vowel shortener", pronunciation: "mai tai-khu", mnemonicHintFr: "Un petit chiffre 8", mnemonicHintEn: "A tiny number 8", mnemonicEmoji: "8️⃣" },
  { letter: "์", type: "vowel", exampleWord: "การันต์", exampleTranslation: "Silencieux", exampleTranslationEn: "Silent mark", pronunciation: "karan", mnemonicHintFr: "Une note de silence", mnemonicHintEn: "A silent note", mnemonicEmoji: "🤫" },

  { letter: "ะ", type: "vowel", exampleWord: "สระ อะ", exampleTranslation: "Vowelle a (courte)", exampleTranslationEn: "Vowel a (short)", pronunciation: "sara a", mnemonicHintFr: "Deux petites bulles (après)", mnemonicHintEn: "Two small bubbles (after)", mnemonicEmoji: "🫧" },
  { letter: "า", type: "vowel", exampleWord: "สระ อา", exampleTranslation: "Vowelle a (longue)", exampleTranslationEn: "Vowel a (long)", pronunciation: "sara aa", mnemonicHintFr: "Une canne (après)", mnemonicHintEn: "A walking stick (after)", mnemonicEmoji: "🦯" },
  { letter: "ิ", type: "vowel", exampleWord: "สระ อิ", exampleTranslation: "Vowelle i (courte)", exampleTranslationEn: "Vowel i (short)", pronunciation: "sara i", mnemonicHintFr: "Un chapeau simple (au-dessus)", mnemonicHintEn: "A simple hat (above)", mnemonicEmoji: "🧢" },
  { letter: "ี", type: "vowel", exampleWord: "สระ อี", exampleTranslation: "Vowelle i (longue)", exampleTranslationEn: "Vowel i (long)", pronunciation: "sara ii", mnemonicHintFr: "Un chapeau avec plume (au-dessus)", mnemonicHintEn: "A hat with a feather (above)", mnemonicEmoji: "🎩" },
  { letter: "ึ", type: "vowel", exampleWord: "สระ อึ", exampleTranslation: "Vowelle ue (courte)", exampleTranslationEn: "Vowel ue (short)", pronunciation: "sara ue", mnemonicHintFr: "Un chapeau avec anneau (au-dessus)", mnemonicHintEn: "A hat with a ring (above)", mnemonicEmoji: "💍" },
  { letter: "ื", type: "vowel", exampleWord: "สระ อือ", exampleTranslation: "Vowelle ue (longue)", exampleTranslationEn: "Vowel ue (long)", pronunciation: "sara uee", mnemonicHintFr: "Un chapeau à double plumes (au-dessus)", mnemonicHintEn: "A double-feather hat (above)", mnemonicEmoji: "🕊️" },
  { letter: "ุ", type: "vowel", exampleWord: "สระ อุ", exampleTranslation: "Vowelle u (courte)", exampleTranslationEn: "Vowel u (short)", pronunciation: "sara u", mnemonicHintFr: "Une goutte d'eau (en dessous)", mnemonicHintEn: "A water drop (below)", mnemonicEmoji: "💧" },
  { letter: "ู", type: "vowel", exampleWord: "สระ อู", exampleTranslation: "Vowelle u (longue)", exampleTranslationEn: "Vowel u (long)", pronunciation: "sara uu", mnemonicHintFr: "Une petite chaussure (en dessous)", mnemonicHintEn: "A small shoe (below)", mnemonicEmoji: "🥿" },
  { letter: "เ", type: "vowel", exampleWord: "สระ เอ", exampleTranslation: "Vowelle e", exampleTranslationEn: "Vowel e", pronunciation: "sara e", mnemonicHintFr: "Un grand poteau (devant)", mnemonicHintEn: "A tall pole (in front)", mnemonicEmoji: "🚩" },
  { letter: "แ", type: "vowel", exampleWord: "สระ แอ", exampleTranslation: "Vowelle ae", exampleTranslationEn: "Vowel ae", pronunciation: "sara ae", mnemonicHintFr: "Deux grands poteaux (devant)", mnemonicHintEn: "Two tall poles (in front)", mnemonicEmoji: "⛩️" },
  { letter: "โ", type: "vowel", exampleWord: "สระ โอ", exampleTranslation: "Vowelle o", exampleTranslationEn: "Vowel o", pronunciation: "sara o", mnemonicHintFr: "Un boomerang (devant)", mnemonicHintEn: "A boomerang (in front)", mnemonicEmoji: "🪃" },
  { letter: "ไ", type: "vowel", exampleWord: "สระ ไอ", exampleTranslation: "Vowelle ai (maimai)", exampleTranslationEn: "Vowel ai (maimai)", pronunciation: "sara ai", mnemonicHintFr: "Une main levée (devant)", mnemonicHintEn: "A raised hand (in front)", mnemonicEmoji: "✋" },
  { letter: "ใ", type: "vowel", exampleWord: "สระ ใอ", exampleTranslation: "Vowelle ai (maimuan)", exampleTranslationEn: "Vowel ai (maimuan)", pronunciation: "sara ai", mnemonicHintFr: "Une feuille enroulée (devant)", mnemonicHintEn: "A rolled leaf (in front)", mnemonicEmoji: "🌿" }
];
